global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts/ads-saas-alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ads-server'
    static_configs:
      - targets: ['ads-server:8000']
    metrics_path: '/metrics'

  - job_name: 'ads-client'
    static_configs:
      - targets: ['ads-client:3000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
